services:
  - type: web
    name: sourceiq-rag-app
    env: python
    buildCommand: "pip install --upgrade pip && pip install torch --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: MALLOC_TRIM_THRESHOLD_
        value: "100000"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: TAVILY_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL_NAME
        value: openai/gpt-oss-120b
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: LOG_LEVEL
        value: INFO
