"""
Module Header
Project: Web-Grounded LLM Content Generation for Engineering Education
Author: Antigravity AI
Purpose: Phase 10 - Integrated stateless web-grounded RAG orchestrator and interactive CLI.
Dependencies: gc, time, typing, sys, config.config, phase1-9 modules
"""

import sys
import gc
import time
import os
import re
import json
from pathlib import Path
from typing import List, Dict, Any, Optional

# Ensure project root is in sys.path
BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

# Package configs and utilities
from config.config import (
    validate_config,
    MAX_SEARCH_RESULTS,
    MAX_SOURCES_TO_SCRAPE,
    TOP_K
)
from cache.cache_manager import CacheManager
from cache.intent_classifier import classify_query
from cache.query_normalizer import normalize_and_hash
from config.trusted_sources import is_domain_trusted
from utils.logger import setup_logger
from utils.helper import (
    print_phase_header,
    print_loading,
    print_processing,
    print_success,
    print_failure,
    print_statistics,
    PhaseTimer
)

# Phase Module Imports
from phase1.web_search import WebSearcher
from phase2.result_filter import ResultFilter
from phase3.website_loader import WebsiteLoader
from phase4.chunker import DocumentChunker
from phase5.embedder import ChunkEmbedder
from phase6.vector_store import VectorStoreManager
from phase7.retriever import SemanticRetriever
from phase8.prompt_builder import PromptBuilder
from phase9.gemini_client import GeminiContentGenerator

# Initialize logger
logger = setup_logger("web_grounded_rag_app")

class WebGroundedRAGPipeline:
    """
    Stateless orchestrator that integrates Phase 1 through 10.
    Conducts web-grounded educational retrieval generation and runs immediate cleanup.
    """

    def __init__(self, cache_manager: Optional[CacheManager] = None) -> None:
        """Initializes and pre-warms the pipeline components."""
        logger.debug("Initializing and pre-warming WebGroundedRAGPipeline components...")
        self.searcher: Optional[WebSearcher] = WebSearcher()
        self.filter_engine: Optional[ResultFilter] = ResultFilter()
        self.cache_manager = cache_manager or CacheManager()
        self.loader: Optional[WebsiteLoader] = WebsiteLoader(self.cache_manager)
        self.chunker: Optional[DocumentChunker] = DocumentChunker()
        self.embedder: Optional[ChunkEmbedder] = ChunkEmbedder()
        self.prompt_builder: Optional[PromptBuilder] = PromptBuilder()
        self.gemini_client: Optional[GeminiContentGenerator] = GeminiContentGenerator()
        self.chat_history: List[Dict[str, str]] = []
        logger.info("Pipeline components pre-warmed and ready.")

    def run_pipeline(
        self,
        query: str,
        user_id: str = "default_user",
        top_k: int = TOP_K,
        max_search_results: int = MAX_SEARCH_RESULTS,
        max_sources_to_scrape: int = MAX_SOURCES_TO_SCRAPE,
        chat_history: Optional[List[Dict[str, str]]] = None
    ) -> Dict[str, Any]:
        """
        Executes the multi-level cached RAG pipeline:
        1. Query Normalization, Hashing, & Intent/Freshness Classification
        2. Stampede Protection (Request Coalescing)
        3. L1 Redis Exact Cache Lookup
        4. L2 MongoDB Persistent Reusable Answer Lookup
        5. L3 SQLite Semantic Vector Cache & Knowledge Reuse Lookup
        6. Full 10-Phase Web-Grounded RAG Execution (on Miss)
        7. Cache Persistence (L1 Redis + L2 Mongo + L3 SQLite) & User History Recording
        """
        logger.info(f"RAG Pipeline Run started for query: '{query}' (user_id='{user_id}')")
        
        timings: Dict[str, float] = {}
        statistics: Dict[str, Any] = {}
        url_metrics: List[Dict[str, Any]] = []
        token_usage: Dict[str, int] = {"input_tokens": 0, "output_tokens": 0, "total_tokens": 0}
        
        db_manager: Optional[VectorStoreManager] = None
        temp_collection_name = f"temp_rag_col_{int(time.time())}"
        
        total_start = time.perf_counter()
        active_history = chat_history if chat_history is not None else self.chat_history

        normalized_query, query_hash = normalize_and_hash(query)
        classification = classify_query(normalized_query)
        freshness = classification.get("freshness", "stable_educational")

        # Request Coalescing (Stampede Protection)
        is_leader, event = self.cache_manager.acquire_coalesce_lock(query_hash)
        if not is_leader and event is not None:
            logger.info(f"[Coalesce] Waiting for in-flight request for hash {query_hash[:12]}...")
            event.wait(timeout=35)
            # Re-check exact L1 Redis or L2 Mongo answer generated by leader
            exact = self.cache_manager.get_exact(query_hash) or self.cache_manager.get_mongo_answer(query_hash)
            if exact:
                exact.setdefault("timings", {})["total_request_ms"] = (time.perf_counter() - total_start) * 1000
                exact["cache_mode"] = "REDIS_HIT"
                self._record_user_history(user_id, query_hash, query, normalized_query, classification, exact, "REDIS_HIT")
                return exact

        cache_timings: Dict[str, float] = {}
        try:
            # Skip stale caches for real-time / dynamic queries (e.g., live prices, news)
            if freshness != "real_time":
                # ── Tier 1: L1 Redis Exact Cache Lookup ─────────────────────────
                lookup_start = time.perf_counter()
                exact = self.cache_manager.get_exact(query_hash)
                cache_timings["exact_cache_lookup_ms"] = (time.perf_counter() - lookup_start) * 1000
                if exact:
                    exact["cache_mode"] = "REDIS_HIT"
                    exact.setdefault("timings", {})["total_request_ms"] = (time.perf_counter() - total_start) * 1000
                    exact["timings"].update(cache_timings)
                    logger.info(
                        f"[CACHE ROUTE] REDIS EXACT HIT | user_id='{user_id}' | "
                        f"normalized_query='{normalized_query}' | query_hash='{query_hash[:12]}...' | "
                        f"intent='{classification.get('intent')}' | scope='{classification.get('scope')}' | "
                        f"similarity=1.000 | cache source=Redis L1"
                    )
                    self._record_user_history(user_id, query_hash, query, normalized_query, classification, exact, "REDIS_HIT")
                    return exact

                # ── Tier 2: L2 MongoDB Persistent Reusable Answer Lookup ─────────
                mongo_start = time.perf_counter()
                mongo_hit = self.cache_manager.get_mongo_answer(query_hash)
                cache_timings["mongo_cache_lookup_ms"] = (time.perf_counter() - mongo_start) * 1000
                if mongo_hit:
                    mongo_hit["cache_mode"] = "MONGODB_HIT"
                    mongo_hit.setdefault("timings", {})["total_request_ms"] = (time.perf_counter() - total_start) * 1000
                    mongo_hit["timings"].update(cache_timings)
                    logger.info(
                        f"[CACHE ROUTE] MONGODB GLOBAL ANSWER HIT | user_id='{user_id}' | "
                        f"normalized_query='{normalized_query}' | query_hash='{query_hash[:12]}...' | "
                        f"intent='{classification.get('intent')}' | scope='{classification.get('scope')}' | "
                        f"similarity=1.000 | cache source=MongoDB L2"
                    )
                    self._record_user_history(user_id, query_hash, query, normalized_query, classification, mongo_hit, "MONGODB_HIT")
                    return mongo_hit

                # ── Tier 3: L3 SQLite Semantic Cache & Knowledge Reuse ───────────
                query_embedding = self.cache_manager.get_query_embedding(query_hash)
                if query_embedding is None:
                    query_embedding = self.embedder.embed_texts([normalized_query])[0]
                    self.cache_manager.set_query_embedding(query_hash, query_embedding)

                decision = self.cache_manager.decide_semantic(query, normalized_query, query_embedding)
                if decision.type == "ANSWER_HIT":
                    hit_resp = self._build_cache_hit_response(decision, cache_timings, total_start)
                    hit_resp["cache_mode"] = "SEMANTIC_HIT"
                    logger.info(f"[SemanticCache] GLOBAL ANSWER HIT | similarity={decision.similarity:.3f}")
                    logger.info(
                        f"[CACHE ROUTE] SQLITE SEMANTIC ANSWER HIT | user_id='{user_id}' | "
                        f"normalized_query='{normalized_query}' | query_hash='{query_hash[:12]}...' | "
                        f"intent='{classification.get('intent')}' | scope='{classification.get('scope')}' | "
                        f"similarity={decision.similarity:.3f} | cache source=SQLite L3"
                    )
                    self._record_user_history(user_id, query_hash, query, normalized_query, classification, hit_resp, "SEMANTIC_HIT")
                    return hit_resp
                if decision.type == "KNOWLEDGE_REUSE":
                    reused = self._run_with_cached_knowledge(
                        query, decision, query_hash, normalized_query, query_embedding,
                        active_history, top_k, total_start, cache_timings
                    )
                    if reused is not None:
                        reused["cache_mode"] = "KNOWLEDGE_REUSE"
                        logger.info(f"[SemanticCache] KNOWLEDGE REUSE HIT | similarity={decision.similarity:.3f}")
                        logger.info(
                            f"[CACHE ROUTE] KNOWLEDGE REUSE | user_id='{user_id}' | "
                            f"normalized_query='{normalized_query}' | query_hash='{query_hash[:12]}...' | "
                            f"intent='{classification.get('intent')}' | scope='{classification.get('scope')}' | "
                            f"similarity={decision.similarity:.3f} | cache source=SQLite L3 Chunks"
                        )
                        self._record_user_history(user_id, query_hash, query, normalized_query, classification, reused, "KNOWLEDGE_REUSE")
                        return reused
            else:
                logger.info(f"[Freshness] Real-time query detected ('{query}'). Bypassing stale cache for fresh search.")
                query_embedding = self.embedder.embed_texts([normalized_query])[0]
        finally:
            if is_leader:
                self.cache_manager.release_coalesce_lock(query_hash)

        logger.info(
            f"[CACHE ROUTE] FULL RAG MISS | user_id='{user_id}' | "
            f"normalized_query='{normalized_query}' | query_hash='{query_hash[:12]}...' | "
            f"intent='{classification.get('intent')}' | scope='{classification.get('scope')}' | "
            f"similarity=0.000 | cache source=None"
        )

        
        try:
            # 0. Configuration Validation
            validate_config()
            
            # Ensure clients are initialized
            if not self.searcher:
                self.searcher = WebSearcher()
                self.filter_engine = ResultFilter()
                self.loader = WebsiteLoader(self.cache_manager)
                self.chunker = DocumentChunker()
                self.embedder = ChunkEmbedder()
                self.prompt_builder = PromptBuilder()
                self.gemini_client = GeminiContentGenerator()

            # ====================================================
            # QUERY REFORMULATION & OPTIMIZATION
            # ====================================================
            print_phase_header("Query Optimization")
            start = time.perf_counter()
            if active_history:
                search_query = self.searcher.reformulate_conversational_query(query, active_history)
                print_success(f"Reformulated query for search: '{search_query}'")
            else:
                search_query = self.searcher.optimize_query(query)
                print_success(f"Optimized search query: '{search_query}'")
            timings["Phase 0 (Query Optimization)"] = time.perf_counter() - start
            
            fallback_mode = False
            raw_search_results = []
            filtered_results = []
            successful_docs = []
            
            try:
                # ====================================================
                # PHASE 1: BROAD WEB SEARCH (TAVILY)
                # ====================================================
                print_phase_header("Phase 1: Broad Web Search (Tavily)")
                t_search = time.perf_counter()
                raw_search_results = self.searcher.search(search_query, max_results=max_search_results)
                timings["Phase 1 (Web Search)"] = time.perf_counter() - t_search
                print_success(f"Discovered {len(raw_search_results)} candidate web sources.")

                # ====================================================
                # PHASE 2: URL VALIDATION & DEDUPLICATION
                # ====================================================
                print_phase_header("Phase 2: URL Validation & Deduplication")
                t_filter = time.perf_counter()
                filtered_results = self.filter_engine.filter_results(raw_search_results)
                timings["Phase 2 (URL Filtering)"] = time.perf_counter() - t_filter
                print_success(f"Retained {len(filtered_results)} unique, valid URLs.")

                if not filtered_results:
                    msg = "I couldn't find enough relevant web content to answer this question reliably."
                    logger.warning(f"Zero valid URLs for query '{query}'. Returning early.")
                    print_failure("No valid web sources were discovered.")
                    print_processing("Stopping pipeline early: zero websites loaded.")
                    
                    total_duration = time.perf_counter() - total_start
                    timings["TOTAL RESPONSE TIME"] = total_duration
                    
                    statistics.update({
                        "Total Duration": f"{total_duration:.3f}s",
                        "Discovered Sources": len(raw_search_results),
                        "Analyzed Sources": 0,
                        "Retrieved Chunks": 0,
                        "Cited Sources": 0,
                        "Response Length (chars)": len(msg),
                        "Status": "No web sources discovered"
                    })
                    
                    return {
                        "success": True,
                        "answer": msg,
                        "sources": [],
                        "timings": timings,
                        "statistics": statistics,
                        "url_metrics": [],
                        "token_usage": token_usage,
                        "error": None
                    }
                    
                # Select Top 5 candidate URLs to scrape
                candidates_to_scrape = filtered_results[:max_sources_to_scrape]
                
                # ====================================================
                # PHASE 3: PARALLEL WEB EXTRACTION
                # ====================================================
                print_phase_header("Phase 3: Parallel Web Extraction")
                start = time.perf_counter()
                urls_to_load = [item["url"] for item in candidates_to_scrape]
                loaded_docs = self.loader.load_multiple(urls_to_load)
                
                url_to_title = {item["url"]: item["title"] for item in candidates_to_scrape}
                for doc in loaded_docs:
                    doc["title"] = url_to_title.get(doc["url"], "Web Source")
                    url_metrics.append({
                        "url": doc["url"],
                        "status": "Success" if doc.get("success") else "Failed",
                        "duration": doc.get("duration", 0.0),
                        "method": doc.get("method", "Unknown"),
                        "chars": len(doc.get("content", ""))
                    })
                    
                timings["Phase 3 (Website Loading)"] = time.perf_counter() - start
                
                successful_docs = [doc for doc in loaded_docs if doc.get("success", False)]
                print_success(f"Successfully scraped and extracted {len(successful_docs)} of {len(urls_to_load)} web pages.")
                
                if not successful_docs:
                    msg = "I couldn't find enough relevant web content to answer this question reliably."
                    logger.warning(f"All web extractions failed for query '{query}'. Returning early.")
                    print_failure("All web extractions failed.")
                    
                    total_duration = time.perf_counter() - total_start
                    timings["TOTAL RESPONSE TIME"] = total_duration
                    
                    statistics.update({
                        "Total Duration": f"{total_duration:.3f}s",
                        "Discovered Sources": len(raw_search_results),
                        "Analyzed Sources": 0,
                        "Retrieved Chunks": 0,
                        "Cited Sources": 0,
                        "Response Length (chars)": len(msg),
                        "Status": "Web page extraction failed"
                    })
                    
                    return {
                        "success": True,
                        "answer": msg,
                        "sources": [],
                        "timings": timings,
                        "statistics": statistics,
                        "url_metrics": url_metrics,
                        "token_usage": token_usage,
                        "error": None
                    }
            except Exception as outer_err:
                logger.warning(f"Web extraction failed: {outer_err}. Falling back to parametric generation.")
                print_failure(f"Web extraction pipeline failed: {outer_err}")
                fallback_mode = True
                
            if fallback_mode:
                print_phase_header("Phase 9: Content Generation (Fallback)")
                start = time.perf_counter()
                fallback_prompt = self.prompt_builder.build_fallback_prompt(query, active_history)
                answer, token_usage = self.gemini_client.generate_response_with_tokens(fallback_prompt)
                timings["Phase 9 (LLM Generation)"] = time.perf_counter() - start
                
                total_duration = time.perf_counter() - total_start
                timings["TOTAL RESPONSE TIME"] = total_duration
                
                statistics.update({
                    "Total Duration": f"{total_duration:.3f}s",
                    "Discovered Sources": 0,
                    "Analyzed Sources": 0,
                    "Retrieved Chunks": 0,
                    "Cited Sources": 0,
                    "Response Length (chars)": len(answer),
                    "Fallback Mode": "Active (parametric response)"
                })
                
                active_history.append({"role": "user", "content": query})
                active_history.append({"role": "assistant", "content": answer})
                
                return {
                    "success": True,
                    "answer": answer,
                    "sources": [],
                    "timings": timings,
                    "statistics": statistics,
                    "url_metrics": url_metrics,
                    "token_usage": token_usage,
                    "error": None
                }
                
            # Grounded RAG Pipeline
            # ====================================================
            # PHASE 4: CHUNKING
            # ====================================================
            print_phase_header("Phase 4: Chunking")
            start = time.perf_counter()
            chunks = self.chunker.chunk_documents(successful_docs)
            timings["Phase 4 (Chunking)"] = time.perf_counter() - start
            print_success(f"Split documents into {len(chunks)} text chunks.")
            
            if not chunks:
                raise ValueError("Document parsing yielded zero text chunks.")

            # Cap chunks if very large to optimize embedding batch size
            max_embedding_candidates = 50
            if len(chunks) > max_embedding_candidates:
                chunks = chunks[:max_embedding_candidates]

            # ====================================================
            # PHASE 5: BATCH EMBEDDING
            # ====================================================
            print_phase_header("Phase 5: Batch Embedding")
            start = time.perf_counter()
            embedded_chunks = self.embedder.embed_chunks(chunks)
            timings["Phase 5 (Embedding Generation)"] = time.perf_counter() - start
            print_success(f"Generated vector representations for {len(embedded_chunks)} chunks.")
            
            # ====================================================
            # PHASE 6: VECTOR STORAGE
            # ====================================================
            print_phase_header("Phase 6: Vector Storage")
            start = time.perf_counter()
            db_manager = VectorStoreManager()
            col = db_manager.create_collection(temp_collection_name)
            db_manager.add_chunks(embedded_chunks)
            timings["Phase 6 (ChromaDB Storage)"] = time.perf_counter() - start
            print_success(f"Ingested vectors into ChromaDB in-memory collection '{temp_collection_name}'.")
            
            # ====================================================
            # PHASE 7: SEMANTIC RETRIEVAL
            # ====================================================
            print_phase_header("Phase 7: Semantic Retrieval")
            start = time.perf_counter()
            retriever = SemanticRetriever(self.embedder, col)
            retrieved_chunks = retriever.retrieve(search_query, top_k=top_k)
            timings["Phase 7 (Retrieval)"] = time.perf_counter() - start
            print_success(f"Retrieved Top-{len(retrieved_chunks)} relevant content chunks.")
            
            # ====================================================
            # PHASE 8: PROMPT BUILDER
            # ====================================================
            print_phase_header("Phase 8: Prompt Builder")
            start = time.perf_counter()
            grounded_prompt = self.prompt_builder.build_prompt(query, retrieved_chunks, active_history)
            timings["Phase 8 (Prompt Building)"] = time.perf_counter() - start
            print_success("Structured grounded prompt constructed successfully.")
            
            # ====================================================
            # PHASE 9: LLM GENERATION
            # ====================================================
            print_phase_header("Phase 9: Content Generation")
            start = time.perf_counter()
            answer, token_usage = self.gemini_client.generate_response_with_tokens(grounded_prompt)
            timings["Phase 9 (LLM Generation)"] = time.perf_counter() - start
            print_success("Grounded response generated.")
            
            # Parse inline citations from the generated answer
            cited_indices = set()
            for match in re.findall(r'\[(?:Source\s*)?(\d+)\]', answer):
                try:
                    idx = int(match) - 1
                    if 0 <= idx < len(retrieved_chunks):
                        cited_indices.add(idx)
                except ValueError:
                    pass

            # Map cited chunks back to unique source URLs
            cited_sources = []
            seen_cited_urls = set()
            
            if cited_indices:
                for idx in sorted(list(cited_indices)):
                    chunk = retrieved_chunks[idx]
                    url = chunk["url"]
                    if url not in seen_cited_urls:
                        seen_cited_urls.add(url)
                        cited_sources.append({"title": chunk["title"], "url": url})
            else:
                for chunk in retrieved_chunks:
                    url = chunk["url"]
                    if url not in seen_cited_urls:
                        seen_cited_urls.add(url)
                        cited_sources.append({"title": chunk["title"], "url": url})

            active_history.append({"role": "user", "content": query})
            active_history.append({"role": "assistant", "content": answer})
            
            # Note: Phase 10 cleanup happens in finally block and its timing is captured there
            total_duration = time.perf_counter() - total_start
            timings["TOTAL RESPONSE TIME"] = total_duration

            statistics.update({
                "Total Duration": f"{total_duration:.3f}s",
                "Discovered Sources": len(raw_search_results),
                "Analyzed Sources": len(successful_docs),
                "Retrieved Chunks": len(retrieved_chunks),
                "Cited Sources": len(cited_sources),
                "Total Chunks": len(chunks),
                "Response Length (chars)": len(answer),
                "Fallback Mode": "Inactive (grounded response)"
            })
            
            result = {
                "success": True,
                "answer": answer,
                "sources": cited_sources,
                "timings": timings,
                "statistics": statistics,
                "url_metrics": url_metrics,
                "token_usage": token_usage,
                "error": None
            }
            self._populate_cache(
                query_hash, normalized_query, query, query_embedding, answer,
                result, embedded_chunks, successful_docs
            )
            result["cache_mode"] = "RAG_MISS"
            self._record_user_history(user_id, query_hash, query, normalized_query, classification, result, "RAG_MISS")
            return result

        except Exception as e:
            logger.error(f"Pipeline failed at run: {e}")
            print_failure(f"Pipeline crashed: {e}")
            total_duration = time.perf_counter() - total_start
            timings["TOTAL RESPONSE TIME"] = total_duration
            return {
                "success": False,
                "answer": "",
                "sources": [],
                "timings": timings,
                "statistics": statistics,
                "url_metrics": url_metrics,
                "token_usage": token_usage,
                "error": str(e)
            }
            
        finally:
            # ====================================================
            # PHASE 10: CLEANUP & TEARDOWN
            # ====================================================
            print_phase_header("Phase 10: Teardown & Cleanup")
            t_clean_start = time.perf_counter()
            
            if db_manager and db_manager.collection:
                try:
                    db_manager.delete_collection()
                except Exception as cleanup_err:
                    logger.warning(f"Error during ChromaDB cleanup: {cleanup_err}")
                    print_failure(f"ChromaDB deletion failed: {cleanup_err}")
            
            db_manager = None
            gc.collect()
            
            t_clean_elapsed = time.perf_counter() - t_clean_start
            timings["Phase 10 (Cleanup)"] = t_clean_elapsed
            
            logger.info("Garbage collection triggered. Memory freed. System stateless.")
            print_success("All temporary memories deleted. System returned to empty state.")

    def _build_cache_hit_response(
        self, decision: Any, cache_timings: Dict[str, float], total_start: float
    ) -> Dict[str, Any]:
        """Builds the normal response shape for a semantic answer hit."""
        timings = dict(cache_timings)
        timings["TOTAL RESPONSE TIME"] = time.perf_counter() - total_start
        return {
            "success": True,
            "answer": decision.answer or "",
            "sources": [],
            "timings": timings,
            "statistics": {"Cache Similarity": f"{decision.similarity:.3f}"},
            "url_metrics": [],
            "token_usage": {"input_tokens": 0, "output_tokens": 0, "total_tokens": 0},
            "error": None,
            "cache_mode": "SEMANTIC_ANSWER_HIT",
        }

    def _run_with_cached_knowledge(
        self, query: str, decision: Any, query_hash: str, normalized_query: str,
        query_embedding: List[float], active_history: List[Dict[str, str]],
        top_k: int, total_start: float, cache_timings: Dict[str, float]
    ) -> Optional[Dict[str, Any]]:
        """Regenerates an answer from validated cached chunks."""
        cached_chunks = self.cache_manager.get_cached_knowledge(decision.chunk_ids)
        valid_chunks = [
            chunk for chunk in cached_chunks
            if is_domain_trusted(chunk.get("metadata", {}).get("url", ""))
        ]
        if not valid_chunks:
            return None

        db_manager = None
        try:
            db_manager = VectorStoreManager()
            collection = db_manager.create_collection(f"reuse_{int(time.time() * 1000)}")
            db_manager.add_chunks(valid_chunks)
            retriever = SemanticRetriever(self.embedder, collection)
            retrieved_chunks = retriever.retrieve(query, top_k=top_k)
            prompt = self.prompt_builder.build_prompt(query, retrieved_chunks, active_history)
            answer, token_usage = self.gemini_client.generate_response_with_tokens(prompt)
            sources = []
            seen_urls = set()
            for chunk in retrieved_chunks:
                url = chunk.get("url", "")
                if url and url not in seen_urls:
                    seen_urls.add(url)
                    sources.append({"title": chunk.get("title", ""), "url": url})

            result = {
                "success": True,
                "answer": answer,
                "sources": sources,
                "timings": {**cache_timings, "TOTAL RESPONSE TIME": time.perf_counter() - total_start},
                "statistics": {"Retrieved Chunks": len(retrieved_chunks)},
                "url_metrics": [],
                "token_usage": token_usage,
                "error": None,
                "cache_mode": "KNOWLEDGE_REUSE",
            }
            classification = classify_query(normalized_query)
            self.cache_manager.save_query_result(
                query_hash, normalized_query, query, classification["intent"],
                classification["scope"], classification["requirements"], answer,
                decision.source_ids, decision.chunk_ids, query_embedding, result
            )
            return result
        except Exception as error:
            logger.warning(f"[Cache] Knowledge reuse failed; continuing with full RAG: {error}")
            return None
        finally:
            if db_manager and db_manager.collection:
                try:
                    db_manager.delete_collection()
                except Exception as cleanup_error:
                    logger.warning(f"[Cache] Knowledge reuse cleanup failed: {cleanup_error}")

    def _populate_cache(
        self, query_hash: str, normalized_query: str, original_query: str,
        query_embedding: List[float], answer: str, pipeline_result: Dict[str, Any],
        embedded_chunks: List[Dict[str, Any]], loaded_docs: List[Dict[str, Any]]
    ) -> None:
        """Persists a successful grounded run without affecting its response."""
        try:
            self.cache_manager.save_full_result(
                query_hash, normalized_query, original_query, query_embedding,
                answer, pipeline_result, embedded_chunks, loaded_docs
            )
        except Exception as error:
            logger.warning(f"[Cache] Failed to populate cache: {error}")

    def _record_user_history(
        self,
        user_id: str,
        query_hash: str,
        original_query: str,
        normalized_query: str,
        classification: Dict[str, Any],
        result: Dict[str, Any],
        cache_status: str
    ) -> None:
        """Helper to record query execution history into MongoDB."""
        try:
            sources = result.get("sources", [])
            self.cache_manager.mongo.save_query_history(
                user_id=user_id,
                query_hash=query_hash,
                original_query=original_query,
                normalized_query=normalized_query,
                intent=classification.get("intent", "concept_explanation"),
                scope=classification.get("scope", ""),
                answer=result.get("answer", ""),
                citations=sources,
                sources_analyzed=result.get("statistics", {}).get("Analyzed Sources", len(sources)),
                sources_used=len(sources),
                cache_status=cache_status,
                is_cacheable=True,
                metadata={"timings": result.get("timings", {})}
            )
        except Exception as e:
            logger.warning(f"[History] Failed to record MongoDB query history: {e}")


def run_app_cli() -> None:
    """Provides a simple interactive command-line interface for the RAG assistant."""
    print("=" * 60)
    print(" WEB-GROUNDED LLM ENGINEERING RAG ASSISTANT CLI ")
    print("=" * 60)
    
    pipeline = WebGroundedRAGPipeline()
    
    if len(sys.argv) > 1:
        query = " ".join(sys.argv[1:])
        print(f"\nProcessing single-shot command line query: '{query}'")
        execute_and_display(pipeline, query)
        return
        
    while True:
        try:
            print("\nEnter an engineering educational topic (or type 'exit' / 'quit' to close):")
            query = input("> ").strip()
            
            if not query:
                continue
            if query.lower() in ("exit", "quit"):
                print("Exiting RAG CLI Assistant. Goodbye!")
                break
                
            execute_and_display(pipeline, query)
            
        except KeyboardInterrupt:
            print("\nExiting RAG CLI Assistant. Goodbye!")
            break

def execute_and_display(pipeline: WebGroundedRAGPipeline, query: str) -> None:
    """Executes the pipeline and prints formatted final output, timing, and statistics."""
    if hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding='utf-8', errors='replace')
            sys.stderr.reconfigure(encoding='utf-8', errors='replace')
        except Exception:
            pass

    print(f"\nRunning grounding pipeline for topic: '{query}'...")
    
    result = pipeline.run_pipeline(query)
    
    if result["success"]:
        print("\n" + "=" * 60)
        print(" GENERATED EDUCATION NOTES ")
        print("=" * 60)
        print(result["answer"])
        print("=" * 60)
        
        # Display Sources Cited
        print("\n--- SOURCES CITED ---")
        if result["sources"]:
            for i, src in enumerate(result["sources"], 1):
                print(f"[{i}] {src['title']}")
                print(f"    Link: {src['url']}")
        else:
            print("No sources could be extracted.")
        print("-" * 60)
        
        # Display Website Loading Performance Report
        print("\n" + "=" * 60)
        print(" WEBSITE LOADING PERFORMANCE REPORT ")
        print("=" * 60)
        url_metrics = result.get("url_metrics", [])
        if url_metrics:
            for i, u_meta in enumerate(url_metrics, 1):
                status_symbol = "✓" if u_meta["status"] == "Success" else "✗"
                print(f"  {status_symbol} URL {i}: {u_meta['duration']:.2f}s | {u_meta['method']} | {u_meta['status']} ({u_meta['chars']} chars)")
                print(f"       {u_meta['url']}")
        else:
            print("  No URL loading metrics recorded.")
        print("-" * 60)
        
        # Display Token Usage Report
        token_usage = result.get("token_usage", {})
        print("\n" + "=" * 60)
        print(" LLM TOKEN USAGE REPORT ")
        print("=" * 60)
        print(f"  Input Tokens  : {token_usage.get('input_tokens', 0)}")
        print(f"  Output Tokens : {token_usage.get('output_tokens', 0)}")
        print(f"  Total Tokens  : {token_usage.get('total_tokens', 0)}")
        print("-" * 60)
        
        # Display Comprehensive Performance Report
        print("\n" + "=" * 60)
        print(" RAG PERFORMANCE REPORT ")
        print("=" * 60)
        print(f"Query: {query}\n")
        timings = result.get("timings", {})
        for phase, t_val in timings.items():
            if phase != "TOTAL RESPONSE TIME":
                print(f"  {phase:<30}: {t_val:.2f} sec")
        print("-" * 60)
        total_t = timings.get("TOTAL RESPONSE TIME", 0.0)
        print(f"  TOTAL RESPONSE TIME           : {total_t:.2f} sec")
        print("=" * 60 + "\n")

    else:
        print_failure(f"Generation failed: {result['error']}")

if __name__ == "__main__":
    run_app_cli()
